### ISSUE TITLE
Errore nell'esecuzione dello script main

### ISSUE THREAD

**Issue by Fedix0** [andry08/ArubaOTP-seed-extractor#14]
Riproducibilità:
-scaricato l'intera repo
-installato le dipendenze
-lanciato python ./scripts/main.py extract [segreto] -q

errore

Traceback (most recent call last):
  File "D:\File scaricati\ArubaOTP-seed-extractor-master\scripts\main.py", line 4, in <module>
    from os import minor
ImportError: cannot import name 'minor' from 'os' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\os.py)

dati aggiuntivi: eseguito su windows 10, versione python 3.10
![rapporto](https://user-images.githubusercontent.com/111634068/185737730-ab7f321e-405c-4ec2-a117-f7bbebc8b138.png)

**Comment by andry08** [comment]
Scusa per il ritardo, effettivamente é successo anche a me, ho risolto reinstallando python, anche se l'errore non aveva senso di esistere.

**Comment by Fedix0** [comment]
Ho provato, nessun risultato.
Ho provato anche ad installare versioni diverse di python ma nulla di fatto.
La mia installazione di python arriva dallo store microsoft, che sia quello la causa?

**Comment by andry08** [comment]
Suppongo di si, ma non mi sono informato particolarmente in merito, non penso comunque sia un errore da parte mia, visto che comunque le funzioni che uso nella lib os sono presenti da python 2, quindi per il momento penso di chiudere l'issue.

**Comment by Fedix0** [comment]
Su che sistema operativo è stato eseguito? Ci sono altre dipendenze che non sono indicate? Anche le cose più banali e scontate.

**Comment by andry08** [comment]
Io utilizzo w11 con python 3.10, con l'ultima versione di venv, per separare le dependencies.
In tutto ciò parlando con un amico ha avuto lo stesso problema e controllando il file os di python mancavano tante funzioni oltre alle variabili major e minor che questo script utilizza per verificare che venga utilizzato python3.
Questo quindi sembra essere un problema di python per windows. Sicuramente a parte rimuovere il check io non posso farci nulla :/
