### ISSUE TITLE
Is it normal that I cannot get the seed more than one time?

### ISSUE THREAD

**Issue by raffaem** [andry08/ArubaOTP-seed-extractor#16]
The first time I call `extract` I'm able to extract the seed.

But the second time it tells me the operation is not valid:

```
$ python ./scripts/main.py extract XXX
Traceback (most recent call last):
  File "./scripts/main.py", line 86, in main
    extract(args.activation_code, args.only_output, args.show_qr)
  File "./scripts/main.py", line 23, in extract
    seed, otp_type, digits, period, counter = extractor.request_otp(activation_code)
  File "./scripts/request.py", line 27, in request_otp
    raise Exception('Seed request failed: [{}] {}'.format(resp1['returncode'], resp1['description']))
Exception: Seed request failed: [0007] Operazione non valida per stato licenza
```

**Comment by raffaem** [comment]
Apparently it is :)

The moboile app tells me that "The activation code has already been used and it is no longher valid. Log in to your control panel (Serlfcare) to reset the OPTP Mobile account, you will receive a new activation code"

**Comment by andry08** [comment]
Yes, that's the problem indeed.
And by the way you can't reset more than a couple of times per day the totp, or else it will give you a non working activation id (and the previous activation id, if you saved it, would still be valid).
