### ISSUE TITLE
Funziona anche con Google Authenticator

### ISSUE THREAD

**Issue by danielegio** [andry08/ArubaOTP-seed-extractor#21]
Ho provato con l'ultima versione di Google Authenticator (sia su Android che su IOS) e scansionando il QR Code che viene generato funziona correttamente anche per quanto riguarda le 8 cifre invece che le 6 standard.

Complimenti per il programma
L'ho trovato molto utile nel mio campo

**Comment by andry08** [comment]
Avevo letto qualcosa a riguardo ma non ho provato personalmente, puoi confermarmi quindi che il codice generato da Google Authenticator funziona oltre ad avere le 8 cifre?
Se così fosse provvederò ad aggiornare il readme, grazie.

**Comment by andry08** [comment]
Ok dopo alcuni test hanno aggiornato anche la versione android in modo che supporti le 8 cifre. Solo quello però.
Tentando di aggiungere un totp sha256 (richiesto per aruba) l'applicazione da un errore di lettura (almeno è esplicito al contrario di altre app che lo ignorano e forniscono codici sbagliati).
Ciò che invece non è esplicito è il period totp, che viene completamente ignorato e messo al default di 30 secondi.
Concludo quindi dicendo che Google Authenticator rimane inutilizzabile per questo progetto.

**Comment by danielegio** [comment]
Io ho provato, scansionando il QR code generato, sia nel caso di SPID che di Firma digitale remota. In entrambi i casi sembrerebbe funzionare sia per quanto riguarda il tempo di validità del codice (nel caso di Spid mi dava 60 secondi, nel caso di firma remota è 30 secondi) sia per lo sha 256.

In giornata eseguo delle verifiche più approfondite utilizzando anche il pannello di configurazione su Aruba per testare OTP.
