### ISSUE TITLE
Funzionamento

### ISSUE THREAD

**Issue by fiorins** [andry08/ArubaOTP-seed-extractor#3]
Buongiorno, non riesco a capire bene il punto 2 e di conseguenza il 3.
Dopo aver installato i requisiti, c'e scritto di aprire il sito web di Aruba e avvia l'accoppiamento. Ho aperto il sito di Aruba da Chrome e ho fatto l'accesso al mio account, dopodiche ?

**Comment by andry08** [comment]
Nella pagina di accoppiamento con l'app vi si trova un qr code, e nella parte in basso a destra si trova un numero abbastanza lungo, basta inserire quel numero nel punto 4.
Se per qualche strano motivo dovesse apparirti solo il qr code, puoi scansionare il codice con una qualsiasi app per leggere codici qr, che ti darà anch'essa il numero da inserire.
Spero di essere stato chiaro, aspetto una conferma da parte tua.

**Comment by fiorins** [comment]
Buongiorno, ci ho riprovato adesso. Credo che questo procedimento sia solo per chi ancora lo deve attivare l'ArubaOTP giusto? Mentre io gia l'ho attivato. Comunque ho inserito il codice di attivazione del mio ArubaOTP, ho copiato il codice di attivazione del mio ArubaOTP credo intendi questo per codice abbastanza lungo: 
![20210413_103040](https://user-images.githubusercontent.com/32281481/114844116-cba5bc80-9dda-11eb-9199-20c16f1e5d0c.jpg)


E l'ho messo nello script, ma mi esce l'errore che vedi qui sotto:
   <img width="1002" alt="Screenshot 2021-04-13 at 10 35 53" src="https://user-images.githubusercontent.com/32281481/114543632-bfdebc80-9c59-11eb-9abb-f1d36a007e0f.png">

**Comment by fiorins** [comment]
Appena rifatto il procedimento, ed ecco cosa esce:
<img width="1280" alt="Screenshot 2021-04-15 at 16 47 47" src="https://user-images.githubusercontent.com/32281481/114889948-e1cb7100-9e0a-11eb-9605-17acbbda6756.png">

**Comment by fiorins** [comment]
Ora questo, dopo che ho cercato di installare questo modulo six che diceva:
<img width="1010" alt="Screenshot 2021-04-15 at 17 54 11" src="https://user-images.githubusercontent.com/32281481/114899977-b9944000-9e13-11eb-8dba-e868ff2ceeca.png">

**Comment by andry08** [comment]
Avendo già un account inserito nell'app, devi cliccare riconfigura se non l'hai già fatto e leggere il codice con un app che non sia aruba, altrimenti il seed viene inviato all'app aruba e provando a usare lo script viene l'errore da te citato.
Questo errore capita a volte anche quando si riconfigura troppe volte di seguito il token, ma dubito sia questo il tuo caso.
In poche parole prova ad usare una semplice app per leggere qr per ottenere il codice, non quella aruba.

**Comment by fiorins** [comment]
Va bene, ora ha funzionato, evidentemente dopo un po di tempo scade qualche certificato e bisogna riconfigurarlo per poter estrarre la chiave, grazie, anche se cosi ho riscontrato la criticità che si potrà usare qualsiasi app tranne quella di ArubaOTP, mentre prima era l'inverso.

**Comment by fiorins** [comment]
Inoltre ho creato il qr code con lo script, ma dall'app Aegis non l'ha riconosciuto e ho dovuto inserire a mano la chiave

**Comment by andry08** [comment]
Strano, visto che l'app può comunque generare il qr code se tieni il file seed nella cartella, anche se l'hai già importato su aegis potresti provare a rigenerare il codice e scansionarlo con un altra app per qr code, effettivamente anche a me ha dato a volte problemi a leggere il codice da aegis, ma provando con un'altra app ho risolto (l'uri che esce dal qr è riconosciuto come apribile dall'app, quindi non ci sono problemi ad importarlo).
Detto questo sono felice tu abbia risolto.
